spring:
  application:
    name: LinkUp
  datasource:
    url: jdbc:h2:mem:linkUpDb
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      true


  jwt:
    secret:aaaaaaaaaaaaa44444444444aaaaaaaaaaaaa

